--- Step 11: Rename EOD Summaries → Daily Summaries
--- Removes the old EOD naming convention in favor of the new trigger-based system.
--- The table is renamed from eod_summaries to daily_summaries.
--- ═══════════════════════════════════════════════════════════════════════════════

-- Rename table
ALTER TABLE eod_summaries RENAME TO daily_summaries;

-- Rename constraint
ALTER TABLE daily_summaries RENAME CONSTRAINT eod_summaries_user_date_unique TO daily_summaries_user_date_unique;

-- Rename index
DROP INDEX IF EXISTS idx_eod_summaries_user_date;
CREATE INDEX IF NOT EXISTS idx_daily_summaries_user_date ON daily_summaries(user_id, date);

-- Update comments
COMMENT ON TABLE daily_summaries IS 'Pre-computed daily summary for instant display; generated by adaptation engine or deep review';
COMMENT ON COLUMN tasks.rescheduled_from IS 'Original due_date before reschedule; null if never rescheduled';
